package it.polimi.ingsw;

public enum MessageType {
    OK,DISCONNECTED,ERROR,
    PICK_PLAYERNAME,
    ASK_NUMBER_OF_PLAYERS,NUMBER_OF_PLAYERS,GAME_CREATED,
    WAIT_FOR_OTHER_PLAYERS,NEW_PLAYER, GAME_JOINED,
    GAME_STARTED,
    SHOW_LEADER_CARDS,CHOOSE_LEADER_CARDS,
    INKWELL_GIVEN,
    ASK_INITIAL_RESOURCES,CHOOSE_INITIAL_RESOURCES,
    WAIT_YOUR_TURN,
    INCREMENT_FAITH_TRACK;
}
