package it.polimi.ingsw;

public enum MessageType {
    NOTENOUGHARGUMENTS,OK,DISCONNECTED,ERROR,
    PICK_PLAYERNAME,JOIN_GAME,CREATE_GAME,NEW_PLAYER,
    START_GAME,
    INKWELLGIVEN,
    ASKINITIALRESOURCE,GIVENINITIALRESOURCES,
    CHOOSELEADERCARDS,LEADERCARDSCHOSEN,
    ENDGAME
}
